services:
  powered-dind:
    build:
      context: .
    env_file:
      - .env
    environment:
      - DOCKER_BUILDKIT=1
      - BUILDKIT_INLINE_CACHE=1
    restart: always
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
